<?php
error_reporting(E_ALL);
ini_set("display_errors", 1);

require_once('../includes/login_funcs.php');
require_once('../includes/db_vars.php');
require_once('../includes/header_footer.php');

// User must be logged in and be someone special.
if (!user_isloggedin() || !user_type_cookieIsSet()) {
  $host = $_SERVER['HTTP_HOST'];
  header("Location: http://{$host}/web/login.php");
  exit;
}
if ($_COOKIE['user_type'] != 1) {
  die('Script aborted #3098. -Programmer.');
}


site_header('Create a Radio Button from Array');

$page_str = <<<EOPAGESTR

<p>Example:</p>

<pre>
function user_type_make_radio_button(&#36;user_type_field_options_in) {
// Returns a string containing the radio button form field
// using the given array of user types. If function fails
// kill the script. The input array is of the type generated by
// the function user_type_generate_eligibles(&#36;user_name_in).

  // If &#36;user_type_field_options_in is not set or is not an array or it is an
  // array which has no elements then abort.
  if (!IsSet(&#36;user_type_field_options_in) || !is_array(&#36;user_type_field_options_in)
    || sizeof(&#36;user_type_field_options_in) &lt; 1) {
    die("Function user_type_make_radio_button failed because it was not passed ".
    "an array.&#92;n - Programmer.");
  }
  
  // Loop which generates the radio button.
  &#36;user_type_button = "";
  reset(&#36;user_type_field_options_in);
  while (&#36;array_cell = each(&#36;user_type_field_options_in))
  {
    &#36;temp_1 = &#36;array_cell['value']['id'];
    &#36;temp_2 = &#36;array_cell['value']['label'];
    &#36;user_type_button .=
    "    &lt;input type=&#92;"radio&#92;" name=&#92;"user_type&#92;" id=&#92;"&#36;temp_1&#92;" value=&#92;"&#36;temp_1&#92;" />" .
    "    &lt;label for=&#92;"&#36;temp_1&#92;">&#36;temp_2&lt;/label>" .
    "&lt;br/>&#92;n";
  }
  
  // Return the radio button string.
  return &#36;user_type_button;
}
</pre>

<p>The same example (cont'd):</p>

<pre>
function user_type_generate_eligibles(&#36;user_name_in) {
  // This function returns an array of arrays. The top level
  // array will be indexed 0 through n-1. Each element of
  // the top level array will contain an array having two
  // indices: id and label which specify a user_type.
  // The top level array is a collection of user types which
  // the user CAN CREATE using the createANewUser.php script.
  // The user types which the user CAN CREATE satisfy two
  // criteria: 1. The user is eligible to have them
  // 2. The user does NOT have them yet.
  // This function returns FALSE if no user types can be
  // returned. It will abort if something goes wrong.
  
  // Initialize index used in array of all user types.
  &#36;id = 1;
  
  // Get all user types from database. Place them in
  // &#36;userType_inSystem[]. If this array is empty then
  // &#36;id will still be 1 after the loop. Otherwise, &#36;id
  // will have value one more than the highest index of
  // the array.
  &#36;query = "SELECT id, label
            FROM available_user_types";
  &#36;result = mysql_query(&#36;query);
  while (&#36;row = mysql_fetch_array(&#36;result)) {
    &#36;userType_inSystem[&#36;id] = &#36;row;
    &#36;id += 1;
  }
</pre>

EOPAGESTR;
echo $page_str;

site_footer();
?>